### ISSUE TITLE
Bitcoin Gold icon request

### ISSUE THREAD

**Issue by FerdiCildiz** [allienworks/cryptocoins#118] opened 2017-12-12 14:30 UTC
Hello there, I already prepared bitcoin gold icon and attached below to make an addition to your project. Can you please add this to iconset?

Thanks in advance!

---

### Coin name (`BTG`)

* link to logo: 
[bitcoingold.svg.zip](https://github.com/allienworks/cryptocoins/files/1551926/bitcoingold.svg.zip)

* official website: 

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment] 2017-12-12 16:43
Duplicate of https://github.com/allienworks/cryptocoins/issues/114

**Closed by allienworks** 2017-12-12 16:43 UTC
