### ISSUE TITLE
viacoin submission

### ISSUE THREAD

**Issue by Vitalynx** [allienworks/cryptocoins#106] opened 2017-11-13 19:05 UTC
To request icons for your coin, please fill info below:

---

### Viacoin (`TICKER`)

* link to logo:  https://bittrexblobstorage.blob.core.windows.net/public/1ac53fb8-3173-46a8-af74-55029492dda4.png
* official website:  http://www.viacoin.org

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): 
* bitcointalk.org thread:  https://bitcointalk.org/index.php?topic=1840789.0

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by allienworks** [comment] 2017-11-13 19:20
Duplicate of https://github.com/allienworks/cryptocoins/issues/91

**Closed by allienworks** 2017-11-13 19:20 UTC
