### ISSUE TITLE
New coin

### ISSUE THREAD

**Issue by nisi1t** [AllienWorks/cryptocoins#167] opened 2018-04-30 11:01 UTC
To request icons for your coin, please fill info below:

---

### Coin name (`TICKER`)
Electroneum / ETN

* link to logo: ???
* official website: https://electroneum.com/

**Optional info** (not mandatory, but saves me time):

* logo color (HEX): `#xxxxxx`
* bitcointalk.org thread: 

---

**Please note:** This is all completely voluntary work, so if you want to _support my efforts and speed up_ the addition of your coin, please donate. Donation addresses can be found [on my website](https://allien.work/donate)

**Comment by AllienWorks** [comment] 2018-07-07 19:20
Duplicate of https://github.com/AllienWorks/cryptocoins/issues/146

**Closed by AllienWorks** 2018-07-07 19:20 UTC
